---
collections:
  - community.postgresql
  - community.general
  - ansible.posix
  - middleware_automation.wildfly
  - middleware_automation.keycloak
  - middleware_automation.infinispan
  - middleware_automation.jws
