---
# Deploy EDVIGE on a tomcat (jws) instance for local use
- name: "Makes EDVIGE available to the local network"
  hosts: jws
  collections:
    - middleware_automation.jws
  vars:
    edvige_checksum: 2685d5512691f5b246a090acee06e4c4
    edvige_home: "{{ jws_home }}/webapps/edvige/"
    jws_user: tomcat
    jws_group: tomcat
    jws_systemd_enabled: True
    jws_java_version: 17
    jws_listen_http_port: 8600
  tasks:
    - name: "Ensure Apache Tomcat is installed and running"
      ansible.builtin.include_role:
        name: middleware_automation.jws.jws
        public: true
  post_tasks:
    - name: "Ensure EDVIGE file is deployed"
      ansible.builtin.include_tasks: tasks/deploy.yml
