---
- name: "Deploy EDVIGE SSO"
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
  vars:
    keycloak_admin_password: "remembertochangeme"
  roles:
    - middleware_automation.keycloak.keycloak

