---
- name: "Setup and maintain a Nginx instance"
  hosts: webservers
  tasks:
    - name: "Ensure nginx package is installed"
      ansible.builtin.package:
        name: nginx
        state: present
      notify: "Ensure nginx is running"

    - name: "Deploy nginx config"
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: "Ensure nginx is reloaded"

  handlers:
    - name: "Ensure nginx is running"
      ansible.builtin.service:
        name: nginx
        state: started

    - name: "Ensure nginx is reloaded"
      ansible.builtin.service:
        name: nginx
        state: reloaded
