---
- name: "Load date into the Edvige app"
  hosts: localhost
  tasks:
    - name: "Use POST ReST endpoint to load data in webapp"
      ansible.builtin.uri:
        url: http://wildfly:8080/edvige/rest/entry
        method: POST
        body: "{{ lookup('ansible.builtin.file','/tmp/entry.json') }}"
        status_code: 200
        body_format: json
      register: status

    - debug:
        var: status
